/**
 * Pure data module for nationality / country selection in the HR app.
 *
 * Contains all ISO 3166-1 alpha-3 country codes paired with their standard
 * Czech short country names (exonyms). No imports — safe to use anywhere.
 */

export interface Nationality {
  code: string;
  name: string;
}

/**
 * All ISO 3166-1 alpha-3 codes with Czech short names.
 * Sorted alphabetically by the Czech name using Czech locale ordering.
 */
export const NATIONALITIES: Nationality[] = [
  { code: "AFG", name: "Afghánistán" },
  { code: "ALA", name: "Ålandy" },
  { code: "ALB", name: "Albánie" },
  { code: "DZA", name: "Alžírsko" },
  { code: "ASM", name: "Americká Samoa" },
  { code: "VIR", name: "Americké Panenské ostrovy" },
  { code: "AND", name: "Andorra" },
  { code: "AGO", name: "Angola" },
  { code: "AIA", name: "Anguilla" },
  { code: "ATA", name: "Antarktida" },
  { code: "ATG", name: "Antigua a Barbuda" },
  { code: "ARG", name: "Argentina" },
  { code: "ARM", name: "Arménie" },
  { code: "ABW", name: "Aruba" },
  { code: "AUS", name: "Austrálie" },
  { code: "AZE", name: "Ázerbájdžán" },
  { code: "BHS", name: "Bahamy" },
  { code: "BHR", name: "Bahrajn" },
  { code: "BGD", name: "Bangladéš" },
  { code: "BRB", name: "Barbados" },
  { code: "BEL", name: "Belgie" },
  { code: "BLZ", name: "Belize" },
  { code: "BLR", name: "Bělorusko" },
  { code: "BEN", name: "Benin" },
  { code: "BMU", name: "Bermudy" },
  { code: "BTN", name: "Bhútán" },
  { code: "BOL", name: "Bolívie" },
  { code: "BES", name: "Bonaire, Svatý Eustach a Saba" },
  { code: "BIH", name: "Bosna a Hercegovina" },
  { code: "BWA", name: "Botswana" },
  { code: "BVT", name: "Bouvetův ostrov" },
  { code: "BRA", name: "Brazílie" },
  { code: "IOT", name: "Britské indickooceánské území" },
  { code: "VGB", name: "Britské Panenské ostrovy" },
  { code: "BRN", name: "Brunej" },
  { code: "BGR", name: "Bulharsko" },
  { code: "BFA", name: "Burkina Faso" },
  { code: "BDI", name: "Burundi" },
  { code: "COK", name: "Cookovy ostrovy" },
  { code: "CUW", name: "Curaçao" },
  { code: "TCD", name: "Čad" },
  { code: "MNE", name: "Černá Hora" },
  { code: "CZE", name: "Česko" },
  { code: "CHN", name: "Čína" },
  { code: "DNK", name: "Dánsko" },
  { code: "COD", name: "Demokratická republika Kongo" },
  { code: "DMA", name: "Dominika" },
  { code: "DOM", name: "Dominikánská republika" },
  { code: "DJI", name: "Džibutsko" },
  { code: "EGY", name: "Egypt" },
  { code: "ECU", name: "Ekvádor" },
  { code: "ERI", name: "Eritrea" },
  { code: "EST", name: "Estonsko" },
  { code: "ETH", name: "Etiopie" },
  { code: "FRO", name: "Faerské ostrovy" },
  { code: "FLK", name: "Falklandy" },
  { code: "FJI", name: "Fidži" },
  { code: "PHL", name: "Filipíny" },
  { code: "FIN", name: "Finsko" },
  { code: "FRA", name: "Francie" },
  { code: "GUF", name: "Francouzská Guyana" },
  { code: "ATF", name: "Francouzská jižní a antarktická území" },
  { code: "PYF", name: "Francouzská Polynésie" },
  { code: "GAB", name: "Gabon" },
  { code: "GMB", name: "Gambie" },
  { code: "GHA", name: "Ghana" },
  { code: "GIB", name: "Gibraltar" },
  { code: "GRD", name: "Grenada" },
  { code: "GRL", name: "Grónsko" },
  { code: "GEO", name: "Gruzie" },
  { code: "GLP", name: "Guadeloupe" },
  { code: "GUM", name: "Guam" },
  { code: "GTM", name: "Guatemala" },
  { code: "GGY", name: "Guernsey" },
  { code: "GIN", name: "Guinea" },
  { code: "GNB", name: "Guinea-Bissau" },
  { code: "GUY", name: "Guyana" },
  { code: "HTI", name: "Haiti" },
  { code: "HMD", name: "Heardův ostrov a McDonaldovy ostrovy" },
  { code: "HND", name: "Honduras" },
  { code: "HKG", name: "Hongkong" },
  { code: "CHL", name: "Chile" },
  { code: "HRV", name: "Chorvatsko" },
  { code: "IND", name: "Indie" },
  { code: "IDN", name: "Indonésie" },
  { code: "IRQ", name: "Irák" },
  { code: "IRN", name: "Írán" },
  { code: "IRL", name: "Irsko" },
  { code: "ISL", name: "Island" },
  { code: "ITA", name: "Itálie" },
  { code: "ISR", name: "Izrael" },
  { code: "JAM", name: "Jamajka" },
  { code: "JPN", name: "Japonsko" },
  { code: "YEM", name: "Jemen" },
  { code: "JEY", name: "Jersey" },
  { code: "ZAF", name: "Jihoafrická republika" },
  { code: "SGS", name: "Jižní Georgie a Jižní Sandwichovy ostrovy" },
  { code: "SSD", name: "Jižní Súdán" },
  { code: "JOR", name: "Jordánsko" },
  { code: "CYM", name: "Kajmanské ostrovy" },
  { code: "KHM", name: "Kambodža" },
  { code: "CMR", name: "Kamerun" },
  { code: "CAN", name: "Kanada" },
  { code: "CPV", name: "Kapverdy" },
  { code: "QAT", name: "Katar" },
  { code: "KAZ", name: "Kazachstán" },
  { code: "KEN", name: "Keňa" },
  { code: "KIR", name: "Kiribati" },
  { code: "CCK", name: "Kokosové ostrovy" },
  { code: "COL", name: "Kolumbie" },
  { code: "COM", name: "Komory" },
  { code: "COG", name: "Kongo" },
  { code: "KOR", name: "Korejská republika" },
  { code: "PRK", name: "Korejská lidově demokratická republika" },
  { code: "XKX", name: "Kosovo" },
  { code: "CRI", name: "Kostarika" },
  { code: "CUB", name: "Kuba" },
  { code: "KWT", name: "Kuvajt" },
  { code: "CYP", name: "Kypr" },
  { code: "KGZ", name: "Kyrgyzstán" },
  { code: "LAO", name: "Laos" },
  { code: "LSO", name: "Lesotho" },
  { code: "LBN", name: "Libanon" },
  { code: "LBR", name: "Libérie" },
  { code: "LBY", name: "Libye" },
  { code: "LIE", name: "Lichtenštejnsko" },
  { code: "LTU", name: "Litva" },
  { code: "LVA", name: "Lotyšsko" },
  { code: "LUX", name: "Lucembursko" },
  { code: "MAC", name: "Macao" },
  { code: "MDG", name: "Madagaskar" },
  { code: "HUN", name: "Maďarsko" },
  { code: "MKD", name: "Severní Makedonie" },
  { code: "MYS", name: "Malajsie" },
  { code: "MWI", name: "Malawi" },
  { code: "MDV", name: "Maledivy" },
  { code: "MLI", name: "Mali" },
  { code: "MLT", name: "Malta" },
  { code: "MAR", name: "Maroko" },
  { code: "MHL", name: "Marshallovy ostrovy" },
  { code: "MTQ", name: "Martinik" },
  { code: "MUS", name: "Mauricius" },
  { code: "MRT", name: "Mauritánie" },
  { code: "MYT", name: "Mayotte" },
  { code: "MEX", name: "Mexiko" },
  { code: "FSM", name: "Mikronésie" },
  { code: "MDA", name: "Moldavsko" },
  { code: "MCO", name: "Monako" },
  { code: "MNG", name: "Mongolsko" },
  { code: "MSR", name: "Montserrat" },
  { code: "MOZ", name: "Mosambik" },
  { code: "MMR", name: "Myanmar" },
  { code: "NAM", name: "Namibie" },
  { code: "NRU", name: "Nauru" },
  { code: "DEU", name: "Německo" },
  { code: "NPL", name: "Nepál" },
  { code: "NER", name: "Niger" },
  { code: "NGA", name: "Nigérie" },
  { code: "NIC", name: "Nikaragua" },
  { code: "NIU", name: "Niue" },
  { code: "NLD", name: "Nizozemsko" },
  { code: "NFK", name: "Norfolk" },
  { code: "NOR", name: "Norsko" },
  { code: "NCL", name: "Nová Kaledonie" },
  { code: "NZL", name: "Nový Zéland" },
  { code: "OMN", name: "Omán" },
  { code: "PAK", name: "Pákistán" },
  { code: "PLW", name: "Palau" },
  { code: "PSE", name: "Palestina" },
  { code: "PAN", name: "Panama" },
  { code: "PNG", name: "Papua-Nová Guinea" },
  { code: "PRY", name: "Paraguay" },
  { code: "PER", name: "Peru" },
  { code: "PCN", name: "Pitcairnovy ostrovy" },
  { code: "CIV", name: "Pobřeží slonoviny" },
  { code: "POL", name: "Polsko" },
  { code: "PRI", name: "Portoriko" },
  { code: "PRT", name: "Portugalsko" },
  { code: "AUT", name: "Rakousko" },
  { code: "REU", name: "Réunion" },
  { code: "GNQ", name: "Rovníková Guinea" },
  { code: "ROU", name: "Rumunsko" },
  { code: "RUS", name: "Rusko" },
  { code: "RWA", name: "Rwanda" },
  { code: "GRC", name: "Řecko" },
  { code: "SPM", name: "Saint-Pierre a Miquelon" },
  { code: "SLV", name: "Salvador" },
  { code: "WSM", name: "Samoa" },
  { code: "SMR", name: "San Marino" },
  { code: "SAU", name: "Saúdská Arábie" },
  { code: "SEN", name: "Senegal" },
  { code: "MNP", name: "Severní Mariany" },
  { code: "SYC", name: "Seychely" },
  { code: "SLE", name: "Sierra Leone" },
  { code: "SGP", name: "Singapur" },
  { code: "SXM", name: "Sint Maarten" },
  { code: "SVK", name: "Slovensko" },
  { code: "SVN", name: "Slovinsko" },
  { code: "SOM", name: "Somálsko" },
  { code: "ARE", name: "Spojené arabské emiráty" },
  { code: "GBR", name: "Spojené království" },
  { code: "USA", name: "Spojené státy americké" },
  { code: "UMI", name: "Menší odlehlé ostrovy USA" },
  { code: "SRB", name: "Srbsko" },
  { code: "LKA", name: "Srí Lanka" },
  { code: "CAF", name: "Středoafrická republika" },
  { code: "SDN", name: "Súdán" },
  { code: "SUR", name: "Surinam" },
  { code: "SHN", name: "Svatá Helena" },
  { code: "LCA", name: "Svatá Lucie" },
  { code: "BLM", name: "Svatý Bartoloměj" },
  { code: "KNA", name: "Svatý Kryštof a Nevis" },
  { code: "MAF", name: "Svatý Martin (FR)" },
  { code: "STP", name: "Svatý Tomáš a Princův ostrov" },
  { code: "VCT", name: "Svatý Vincenc a Grenadiny" },
  { code: "SWZ", name: "Svazijsko" },
  { code: "SYR", name: "Sýrie" },
  { code: "SLB", name: "Šalomounovy ostrovy" },
  { code: "ESP", name: "Španělsko" },
  { code: "SJM", name: "Špicberky a Jan Mayen" },
  { code: "SWE", name: "Švédsko" },
  { code: "CHE", name: "Švýcarsko" },
  { code: "TJK", name: "Tádžikistán" },
  { code: "TZA", name: "Tanzanie" },
  { code: "THA", name: "Thajsko" },
  { code: "TWN", name: "Tchaj-wan" },
  { code: "TGO", name: "Togo" },
  { code: "TKL", name: "Tokelau" },
  { code: "TON", name: "Tonga" },
  { code: "TTO", name: "Trinidad a Tobago" },
  { code: "TUN", name: "Tunisko" },
  { code: "TUR", name: "Turecko" },
  { code: "TKM", name: "Turkmenistán" },
  { code: "TCA", name: "Turks a Caicos" },
  { code: "TUV", name: "Tuvalu" },
  { code: "UGA", name: "Uganda" },
  { code: "UKR", name: "Ukrajina" },
  { code: "URY", name: "Uruguay" },
  { code: "UZB", name: "Uzbekistán" },
  { code: "CXR", name: "Vánoční ostrov" },
  { code: "VUT", name: "Vanuatu" },
  { code: "VAT", name: "Vatikán" },
  { code: "VEN", name: "Venezuela" },
  { code: "VNM", name: "Vietnam" },
  { code: "TLS", name: "Východní Timor" },
  { code: "WLF", name: "Wallis a Futuna" },
  { code: "ZMB", name: "Zambie" },
  { code: "ESH", name: "Západní Sahara" },
  { code: "ZWE", name: "Zimbabwe" },
];

/**
 * Returns the Czech name for an ISO 3166-1 alpha-3 code (case-insensitive),
 * or the original code unchanged if no match is found.
 */
export function nationalityName(code: string): string {
  if (!code) return code;
  const upper = code.toUpperCase();
  const match = NATIONALITIES.find((n) => n.code === upper);
  return match ? match.name : code;
}

// ── Backend-only helper (added for PDF form fills) ──────────────────────────
const NAME_BY_CODE: Record<string, string> = Object.fromEntries(
  NATIONALITIES.map((n) => [n.code, n.name])
);

/** "CZE" → "CZE - Česko". Unknown/empty codes are returned trimmed as-is. */
export function formatNationality(code: string | null | undefined): string {
  const c = (code ?? "").trim();
  if (!c) return "";
  const name = NAME_BY_CODE[c];
  return name ? `${c} - ${name}` : c;
}
