import { Router } from "express";
import * as admin from "firebase-admin";
import { FieldValue } from "firebase-admin/firestore";
import { requireAuth, AuthRequest } from "../middleware/auth";
import { requirePermission } from "../auth/permissions";

/**
 * Předávací protokol warnings — the admin/director review surface for the shift
 * handover. Two `type`s share this collection, both generated by the handover
 * sign flow (functions/src/routes/handovers.ts) and read (acknowledged) in place
 * via a `read` flag, mirroring routes/alerts.ts:
 *   - "chain" (Nenavazující předání) — syncChainWarning: a shift's Předal signer
 *     differs from the previous shift's Převzal signer. Legacy docs predating the
 *     `type` field are treated as "chain" by the client.
 *   - "late"  (Pozdní příchod)       — syncLateWarning: the Převzal signature landed
 *     after the next shift's start (19:00 night / 07:00 day, Europe/Prague).
 */
export const handoverWarningsRouter = Router();

const db = () => admin.firestore();
const COL = "handoverWarnings";

// GET /api/handover-warnings — newest first. Admin/director review surface.
handoverWarningsRouter.get(
  "/",
  requireAuth,
  requirePermission("changeRequests.review"),
  async (_req: AuthRequest, res) => {
    const snap = await db().collection(COL).orderBy("createdAt", "desc").limit(500).get();
    res.json(snap.docs.map((d) => ({ id: d.id, ...d.data() })));
  }
);

// GET /api/handover-warnings/unread-count — unread total (both types) for the
// Upozornění tab + sidebar badge. Single-field filter → no composite index.
handoverWarningsRouter.get(
  "/unread-count",
  requireAuth,
  requirePermission("changeRequests.review"),
  async (_req: AuthRequest, res) => {
    const snap = await db().collection(COL).where("read", "==", false).count().get();
    res.json({ count: snap.data().count });
  }
);

// POST /api/handover-warnings/read — mark the given ids read (or unread).
handoverWarningsRouter.post(
  "/read",
  requireAuth,
  requirePermission("changeRequests.review"),
  async (req: AuthRequest, res) => {
    const body = req.body as { ids?: unknown; read?: unknown };
    const ids = Array.isArray(body.ids) ? body.ids.filter((x): x is string => typeof x === "string") : [];
    const read = body.read !== false; // default true
    if (ids.length === 0) {
      res.status(400).json({ error: "Nic k označení." });
      return;
    }
    const col = db().collection(COL);
    const snaps = await Promise.all(ids.map((id) => col.doc(id).get()));
    const batch = db().batch();
    let n = 0;
    for (const s of snaps) {
      if (!s.exists) continue;
      batch.update(s.ref, {
        read,
        readAt: read ? FieldValue.serverTimestamp() : null,
        readBy: read ? req.uid : null,
      });
      n++;
    }
    if (n > 0) await batch.commit();
    res.json({ ok: true, updated: n });
  }
);
